from app.extentions import db
from datetime import datetime
from app.models.projects import Project


# mongoengine database model for User
# primary key - ObjectId autogenerated


class User(db.Document):
	name = db.StringField(max_length=120, required=True)
	email = db.EmailField(max_length=50, required=True, unique=True)
	age = db.IntField()
	occupation = db.StringField()
	place = db.StringField()
	projects = db.ListField(db.ReferenceField(Project))
	created_at = db.DateTimeField(default=datetime.now())
